apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: my-hello-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CLOUD_NAME
              value: "kind-cloud-b"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5