apiVersion: v1
kind: ConfigMap
metadata:
  name: router-config
  namespace: app
data:
  nginx.conf: |
    events {}

    http {
      upstream cloud_a {
        server host.docker.internal:9001 max_fails=1 fail_timeout=5s;
      }

      upstream cloud_b {
        server host.docker.internal:9002 max_fails=1 fail_timeout=5s;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://cloud_a;
          proxy_next_upstream error timeout http_502 http_503 http_504;
          proxy_connect_timeout 2s;
          error_page 502 503 504 = @failover;
        }

        location @failover {
          proxy_pass http://cloud_b;
        }
      }
    }